### ISSUE TITLE
Non-ops can't join

### ISSUE THREAD

**Issue by TomGrozev** [Double0negative/Survival-Games#113]
Non-Op's can't join the game. I have given them permission, and even full permission to the plugin and that didn't work. Then I tried giving them op and that worked! Please Help!

**Comment by TomGrozev** [comment]
Anyone?

**Comment by Johlian** [comment]
What permission plugin are you using?
First make sure that the permissions are entered in right.
Check the server log for any errors due to the permission.
Make sure the permission plugin is not over riding your permissions, May be due to a Global ranking file being in control of the permission.

**Comment by sshipway** [comment]
You need to grant permission `sg.arena.join.1` to allow joining arena 1.  Using `.*` or `.all` doesn't work.
