### ISSUE TITLE
/sg addwall

### ISSUE THREAD

**Issue by columb** [Double0negative/Survival-Games#21]
This command has been replaced by /sg addwal <arenaid>
Even if I try to use /sg addwall 1. Build #23.

**Comment by DerpgonCz** [comment]
Pull Request #20 fixes this

**Comment by columb** [comment]
@DragonCzz do you have compiled version of your pull somewhere? I need it pretty bad.

**Comment by DerpgonCz** [comment]
You can pull from my repo and compile it yourself, but I suppose you are not good in this think, so I uploaded it for you:
http://www.mediafire.com/?r209z37qd0rqiyj

It has something more, I tested it but it is not official, handle with caution.

**Comment by columb** [comment]
@DragonCzz  Eh... Just tried to run it on clean setup for tests http://pastebin.com/fwGTba5w

**Comment by Double0negative** [comment]
Fixed in #23
