### ISSUE TITLE
[BUG] Errors When Trying to do /sg setspawn

### ISSUE THREAD

**Issue by WoAnerges** [Double0negative/Survival-Games#42]
http://pastebin.com/nNWDxVyx

CraftBukkit version git-Spigot-866 (MC: 1.5.2) (Implementing API version 1.5.2-R0.2-SNAPSHOT)

 SurvivalGames version 0.5.8.30

**Comment by DerpgonCz** [comment]
Try to delete your messages.yml, restart your server and report back

**Comment by WoAnerges** [comment]
This is my messages.yml http://pastebin.com/sCecngrc
What is wrong with it?

**Comment by WoAnerges** [comment]
After re-creating the messages.yml it now works. Still, it does not solve the problem, right? Or does it?

**Comment by DerpgonCz** [comment]
If it works now, it solved your problem. But the problem persist, it is in wrong reading config version file and therefore failing to re-create it. We are working on the issue.
